# Generated by Django 4.0.3 on 2022-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0003_alter_estudiante_email_alter_profesor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
